name: CasinoPlugin
version: '${version}'

commands:
  casino:
    description: Drehe an der Slot Maschine
    usage: /casino
    aliases: [slotmachine, sm]
  stash:
    description: Öffnet deinen Casino Stash
    usage: /stash

softdepend: [Citizens]

main: de.firstminecoding.casinoPlugin.CasinoPlugin
api-version: '1.21.11'
load: POSTWORLD
